from __future__ import annotations


from typing import Any, Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class UnitProtocol(Protocol):
    """Protocol class for classes that implement the interface of cf_units.Unit

    https://cf-units.readthedocs.io/en/latest/unit.html
    https://cf-units.readthedocs.io/en/latest/_modules/cf_units.html#Unit
    """

    __slots__ = ()

    category: int | None
    ut_unit: Any
    calendar: str | None
    origin: str | None

    def __init__(self, unit: str, calendar: str | None = None) -> None: ...

    def is_time(self) -> bool: ...

    def is_vertical(self) -> bool: ...

    def is_udunits(self) -> bool: ...

    def is_time_reference(self) -> bool: ...

    def is_long_time_interval(self) -> bool: ...

    def title(self, value: float) -> str: ...

    @property
    def modulus(self) -> float | None: ...

    def is_convertible(self, other: str, UnitProtocol) -> bool: ...

    def is_dimensionless(self) -> bool: ...

    def is_unknown(self) -> bool: ...

    def is_no_unit(self) -> bool: ...

    def format(self, option: int | list[int] | None = None) -> str: ...

    @property
    def name(self) -> str: ...

    @property
    def symbol(self) -> str: ...

    @property
    def definition(self) -> str: ...

    def offset_by_time(self, origin: float) -> UnitProtocol: ...

    def invert(self) -> UnitProtocol: ...

    def root(self, root: int) -> UnitProtocol: ...

    def log(self, base: float) -> UnitProtocol: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __add__(self, other: float) -> UnitProtocol: ...

    def __sub__(self, other: float) -> UnitProtocol: ...

    def __mul__(self, other: float | str | UnitProtocol) -> UnitProtocol: ...

    def __div__(self, other: float | str | UnitProtocol) -> UnitProtocol: ...

    def __truediv__(self, other: float | str | UnitProtocol) -> UnitProtocol: ...

    def __pow__(self, power: float) -> UnitProtocol: ...

    def __eq__(self, other: object) -> bool: ...

    def __ne__(self, other: object) -> bool: ...

    def change_calendar(self, calendar: str) -> UnitProtocol: ...

    def convert(
        self,
        value: float | np.ndarray,
        other: str,
        UnitProtocol,
        ctype: Any = np.float64,
        inplace: bool = False,
    ) -> float | np.ndarray: ...

    @property
    def cftime_unit(self) -> str: ...

    def date2num(self, date: Any) -> float | np.ndarray: ...

    def num2date(
        self,
        time_value: float | np.ndarray,
        only_use_cftime_datetimes: bool = True,
        only_use_python_datetimes: bool = False,
    ) -> Any | np.ndarray: ...

    def num2pydate(self, time_value: float | np.ndarray) -> Any | np.ndarray: ...
