from pathlib import Path

CFG = dict(
    proj_id="cams2-83",
    public=True,
    json_basedir=str(Path("../../data").absolute()),
    coldata_basedir=str(Path("../../coldata").absolute()),
    reanalyse_existing=True,
    only_json=False,
    add_model_maps=False,
    only_model_maps=False,
    clear_existing_json=False,
    raise_exceptions=False,
    use_cams2_83=True,
    filter_name="ALL-wMOUNTAINS",
    ts_type="hourly",
    map_zoom="Europe",
    freqs=["hourly", "daily"],  # Possible frequencies
    periods=[
        "2021-2022"
    ],  # Periodes, can be single years or range, e.g. 2010-2015. EMEP only supports single years as of now
    main_freq="hourly",  # default frequency to use. This will be overwritten in most of the observation options (see below)
    use_diurnal=False,
    resample_how={"vmro3": {"daily": {"hourly": "max"}}},
    zeros_to_nan=True,
    colocate_time=False,
    obs_remove_outliers=False,
    model_remove_outliers=False,
    harmonise_units=True,
    regions_how="country",
    annual_stats_constrained=False,
    weighted_stats=False,
    forecast_evaluation=True,
    forecast_days=4,
    use_fairmode=True,
    drop_stats=("mb", "mab"),
    var_order_menu=[
        "vmrno2",
        "vmro3max",
        "vmro3",
        "conco3",
        "vmrox",
        "concso2",
        "vmrco",
        "concpm25",
        "concpm10",
        "concso4",
        "concNtno3",
        "concNtnh",
        "concNnh3",
        "concNnh4",
        "concNhno3",
        "concNno3pm25",
        "concNno3pm10",
        "concsspm25",
        "concsspm10",
        "concCecpm25",
        "concCocpm25",
        "wetoxs",
        "wetrdn",
        "wetoxn",
        "pr",
        "drysox",
        "dryrdn",
        "dryoxn",
        "dryo3",
        "dryvelo3",
    ],
    min_num_obs=dict(
        daily=dict(hourly=18),
    ),
)

