[emep_variables]
abs550aer = "AAOD_550nm"
abs550bc = "AAOD_EC_550nm"
absc550aer = "AbsCoeff"
absc550dryaer = "AbsCoeff"
ac550aer = "AbsCoef_surf"
drybc = "DDEP_EC_m2Grid"
drydust = "DDEP_DUST_m2Grid"
drynh4 = "DDEP_NH4_f_m2Grid"
dryno3 = "DDEP_TNO3_m2Grid"
dryoa = "DDEP_OM25_m2Grid"
dryso2 = "DDEP_SO2_m2Grid"
dryso4 = "DDEP_SO4_m2Grid"
dryoxs = "DDEP_SOX_m2Grid"
dryrdn = "DDEP_RDN_m2Grid"
dryoxn = "DDEP_OXN_m2Grid"
dryss = "DDEP_SS_m2Grid"
ec550aer = "EXT_550nm"
ec550dryaer = "EXTdry_550nm"
emidust = "DUST_flux"
emisnox = "Emis_mgm2_nox"
emisox = "Emis_mgm2_sox"
loadbc = "COLUMN_EC_kmax"
loaddust = "COLUMN_DUST_kmax"
loadnh4 = "COLUMN_NH4_F_kmax"
loadno3 = "COLUMN_TNO3_kmax"
loadoa = "COLUMN_OM25_kmax"
loadso2 = "COLUMN_SO2_kmax"
loadso4 = "COLUMN_SO4_kmax"
loadss = "COLUMN_SS_kmax"
mmrbc = "D3_mmr_EC"
mmrdust = "D3_mmr_DUST"
mmrnh4 = "D3_mmr_NH4_F"
mmrno3 = "D3_mmr_TNO3"
mmroa = "D3_mmr_OM25"
mmrso2 = "D3_mmr_SO2"
mmrso4 = "D3_mmr_SO4"
mmrss = "D3_mmr_SS"
od350aer = "AOD_350nm"
od440aer = "AOD_440nm"
od550aer = "AOD_550nm"
od550bc = "AOD_EC_550nm"
od550dust = "AOD_DUST_550nm"
od550lt1aer = "AOD_PMFINE_550nm"
od550nh4 = "AOD_NH4_F_550nm"
od550no3 = "AOD_TNO3_550nm"
od550oa = "AOD_OC_550nm"
od550so4 = "AOD_SO4_550nm"
od550ss = "AOD_SS_550nm"
od870aer = "AOD_870nm"
concaeroh2o = "SURF_PM25water"
concbcc = "SURF_ug_ECCOARSE"
concbcf = "SURF_ug_ECFINE"
concdust = "SURF_ug_DUST"
conchno3 = "SURF_ug_HNO3"
concnh3 = "SURF_ug_NH3"
concnh4 = "SURF_ug_NH4_F"
concnh4coarse = "SURF_ug_NH4_F"
concnh4fine = "SURF_ug_NH4_F"
concno2 = "SURF_ug_NO2"
concno3c = "SURF_ug_NO3_C"
concno3f = "SURF_ug_NO3_F"
concno = "SURF_ug_NO"
conco3 = "SURF_ug_O3"
concoac = "SURF_ug_PM_OMCOARSE"
concoaf = "SURF_ug_PM_OM25"
concpm10 = "SURF_ug_PM10_rh50"
concpm25 = "SURF_ug_PM25_rh50"
concrdn = "SURF_ugN_RDN"
concso2 = "SURF_ug_SO2"
concso4 = "SURF_ug_SO4"
concso4c = "SURF_ug_SO4"
concso4coarse = "SURF_ug_SO4"
concso4fine = "SURF_ug_SO4"
concss = "SURF_ug_SS"
# concsspm25=SURF_ug_SEASALT_F
concssf = "SURF_ug_SEASALT_F"
concssc = "SURF_ug_SEASALT_C"
concCocpm25 = "SURF_ugC_PM_OM25"
concecpm25 = "SURF_ug_ECFINE"
vmro32m = "SURF_2MO3"
vmro3max = "SURF_MAXO3"
vmro3 = "SURF_ppb_O3"
vmrco = "SURF_ppb_CO"
vmrc2h6 = "SURF_ppb_C2H6"
vmrc2h4 = "SURF_ppb_C2H4"
vmrhcho = "SURF_ppb_HCHO"
vmrglyoxal = "SURF_ppb_GLYOX"
vmrisop = "SURF_ppb_C5H8"
wetbc = "WDEP_EC"
wetdust = "WDEP_DUST"
wetnh4 = "WDEP_NH4_f"
wetno3 = "WDEP_TNO3"
wetoa = "WDEP_OM25"
wetoxn = "WDEP_OXN"
wetrdn = "WDEP_RDN"
wetso2 = "WDEP_SO2"
wetso4 = "WDEP_SO4"
wetoxs = "WDEP_SOX"
wetss = "WDEP_SS"
z3d = "Z_MID"
prmm = "WDEP_PREC"
concCocFine = "SURF_ugC_PM_OM25"
concCocCoarse = "SURF_ugC_PM_OMCOARSE"
concecFine = "SURF_ug_ECFINE"
concecCoarse = "SURF_ug_ECCOARSE"
concoxn = "SURF_ugN_OXN"
vmrno = "SURF_ppb_NO"