# The left hand side is the aerocom variable name, the right hand side is the CMIP variable name
# names with "3d" in them indicate a 3d variable
# for pyaerocom 2d fields and CMIP 3d fields, pyaerocom will try to determine the ground level and return that
# using the same CMIP variable for serveral pyaerocom variables is possible
[cmip_variables]
od550aer = "od550aer"
od550bc = "od550bc"
od550dust = "od550dust"
od550lt1aer = "od550lt1aer"
od550nh4 = "od550nh4"
od550no3 = "od550no3"
od550oa = "od550oa"
od550so4 = "od550so4"
od550ss = "od550ss"
od870aer = "od870aer"
vmro3 = "o3"
concso2 = "so2"
#concso4 = "mmrso4"
concno2 = "no2"
concno = "no"
concnh3 = "nh3"
#conc = ""
# profile
vmro33d = "o3"

# the following defines which additional variables are needed for a given aerocom variable
# to adjust the CMIP units to pyaerocom units
[aux_info]
[aux_info.concso4]
aux_vars = ["mmrso4_surf", "ps", "tas"]
units = "ug m-3"
# Not sure if we need this. This is at 15 degrees C
formula = "(x.ps/287.0/x.tas)*x.mmrso4[:,{LL},:,:]*1e9"

[aux_info.tas]
aux_vars = ["ta"]
units = "K"
how = "surface layer"
# Not sure if we need this.
formula = "x.ts[:,{LL},:,:]"

[aux_info.mmrso4_surf]
aux_vars = ["mmrso4"]
units = "kg kg-1"
how = "surface layer"
# Not sure if we need this.
formula = "x.mmrso4[:,{LL},:,:]"

# aliases for CMIP variables
[cmip_aliases]
[cmip_aliases.ts]
alias = ["ta"]
layer = "lowest"